### ISSUE TITLE
How to use MongoDB's ObjectID

### ISSUE THREAD

**Issue by tbergeron** [Raynos/mongo-col#1]
Hi!

I'm trying to do this kind of thing (that I used to do with MongoJs)

``` javascript
this.update({ _id: this.ObjectId(project._id) }, {
  $set: { code: project_code, name: project.name }
});
```

Is there any equivalent with mongo-col?

Thanks!

**Comment by Raynos** [comment]
mongo-col is a thin abstraction, if your trying to use things outside the abstraction use the mongodb native driver directly.

```
var mongodb = require("mongodb"),
    ObjectID = mongodb.ObjectID,
    Col = require("mongo-col")("Col")

Col.update({ _id: ObjectID(project._id) }, {
    $set: { code: project_code, name: project.name }
})
```

**Comment by tbergeron** [comment]
For some unknown reason, ObjectId is always giving me undefined with mongodb.ObjectId, I'll check out the API maybe it's somewhere else or named something else.

Thanks for the help as always!!!

**Comment by Raynos** [comment]
@tbergeron If I spell `mongodb.ObjectID` (capital D) correctly then it's not undefined

**Comment by tbergeron** [comment]
Oh crap, I'm dumb. Thanks!

**Comment by emilb604** [comment]
i guess that makes 2 :D

**Comment by gselvamary** [comment]
const ObjectId - require('mongodb').ObjectID;

and use it as 
db.collectionName.deleteOne({ _id: ObjectId(req.body.id) });
